[package]
name = "gbc-m4"
version = "0.1.0"
authors = ["fuckm <samwatkins94@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
